config/routes.rb
Rails.application.routes.draw do
  resources :samples
  resources :paids
  resources :charges
  get "/bass" => "bass#index"
  get "/drums" => "drums#index"
  get "/effects" => "effects#index"
  get "/guitars" => "guitars#index"
  get "/synths" => "synths#index"
  get "/vocals" => "vocals#index"
  get "/members/:id" => "members#show"
  get "/users/payment_profile" => "users#payment_profile"
  get "/marketplaces" => "marketplaces#index"




get "settings/payment-info/users/auth/stripe_connect/callback", to:"users#stripe_callback"

  devise_for :users, :controllers => {:registrations => "registrations"}


  resources :samples do
    member do
      put "like", to: "samples#upvote"
      put "dislike", to: "samples#downvote"
    end
  end
  resources :paids do
    member do
      put "like", to: "paids#upvote"
      put "dislike", to: "paids#downvote"
    end
  end


  devise_scope :user do
  get 'login', to: 'devise/sessions#new'
  get 'signup', to: 'devise/registrations#new'

  authenticated  do
    root to: 'samples#index'
  end

  unauthenticated  do
    root to: 'devise/sessions#new'
  end

end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/paid.rb
class Paid < ApplicationRecord
  belongs_to :user
  mount_uploader :audio, AudioUploader
  acts_as_votable

end

app/models/sample.rb
class Sample < ApplicationRecord
  mount_uploader :audio, AudioUploader
  belongs_to :user
  acts_as_votable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :samples
  has_many :paids
  serialize :stripe_account_status, JSON
  acts_as_voter
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


def connected?; !stripe_user_id.nil?; end

def standalone?; stripe_account_type == 'standalone'; end
def oauth?; stripe_account_type == 'oauth'; end

def manager
  case stripe_account_type
  when 'standalone' then StripeStandalone.new(self)
  when 'oauth' then StripeOauth.new(self)
  end
end

def can_accept_charges?
  return true if oauth?
  return true if standalone? && stripe_account_status['charges_enabled']
  return false
end

end

app/controllers/bass_controller.rb
class BassController < ApplicationController
  def index
    @samples = Sample.where(category: "bass")
  end
end

app/controllers/drums_controller.rb
class DrumsController < ApplicationController
  def index
    @samples = Sample.where(category: "drums")
  end
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  before_action :set_sample, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

  def upvote
    @sample.upvote_by current_user
    redirect_back fallback_location: root_path
  end

  def downvote
    @sample.downvote_by current_user
    redirect_back fallback_location: root_path
  end

    def index
      @samples = Sample.all
    end

    def new
      @sample = Sample.new
    end

    def create
      @sample = Sample.new(sample_params)
      @sample.user_id = current_user.id
      respond_to do |format|
        if @sample.save
          format.html { redirect_to @sample}
          format.json { render :show, status: :created, location: @sample }
        else
          format.html { render :new }
          format.json { render json: @sample.errors, status: :unprocessable_entity }
        end
      end
    end

    def show
    end

    def edit
    end

    def update

       respond_to do |format|
         if @sample.update(sample_params)
           format.html { redirect_to @sample, notice: 'Sample was successfully updated.' }
           format.json { render :show, status: :ok, location: @sample }
         else
           format.html { render :edit }
           format.json { render json: @sample.errors, status: :unprocessable_entity }
         end
       end
     end

     def destroy
      @sample.destroy
      respond_to do |format|
        format.html { redirect_to samples_url, notice: 'Sample was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

      def set_sample
        @sample = Sample.find(params[:id])
      end

      def sample_params
        params.require(:sample).permit(:title, :audio,:user_id, :category,:payment)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bass_helper.rb
module BassHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/drums_helper.rb
module DrumsHelper
end

app/helpers/effects_helper.rb
module EffectsHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/guitars_helper.rb
module GuitarsHelper
end

app/helpers/marketplaces_helper.rb
module MarketplacesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/paids_helper.rb
module PaidsHelper
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/helpers/stripe_helper.rb
module StripeHelper
end

app/helpers/synths_helper.rb
module SynthsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vocals_helper.rb
module VocalsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/samples/edit.html.erb
<h1>Samples#edit</h1>
<p>Find me in app/views/samples/edit.html.erb</p>

app/views/samples/index.html.erb
<div class="sampleImage">
    <div id="recentTitle" class="col-m-2 col-md-offset-4">
      <h2>Most Recent Samples</h2>
    </div>

<div id="catWrap" class="row">
<% @samples.each do |f| %>
  <div class="catUser"><strong><%= f.user.username %></strong></div>
  <a id="catUser" class="btn btn-info btn-xs" href="/samples/<%=f.id %>"><%=f.title %></a>
  <div>
    <audio class="downloadAudio" controls controlsList="nodownload">
      <source src="<%=f.audio.url()%>">
    </audio>
  </div>
  <div id="catDownload" class="btn btn-info btn-xs"><%= link_to "Download", f.audio.url() %></div>
  <div class="catLike">
    <%= link_to like_sample_path(f), method: :put do %>
      <i class="glyphicon glyphicon-thumbs-up"></i>
    <%= f.get_upvotes.size %>
  <% end %>
    <%= link_to dislike_sample_path(f), method: :put do %>
      <i class="glyphicon glyphicon-thumbs-down"></i>
    <%= f.get_downvotes.size %>
  <% end %>
</div>
  <hr>
<% end %>
</div>

</div>

app/views/samples/new.html.erb
<div id="outwrapper">
  <div id="sign-image" class="container">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <div class="form-content">
          <h2 class="out" class="text-center">Post Sample</h2>
<div class="formWrap">
<%= bootstrap_form_for @sample do |f| %>
  <div>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.file_field :audio%>
  </div>
  <div id="dropdownForm">
    <%= f.select :category, ['drums', 'synths', "vocals", "guitars", "bass", "effects"] %>
  </div>

  <%= f.submit %>
<% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/samples/show.html.erb
<div class="profileImage">

<div id="paidShow" class="row">
  <div class="sampleTitle"><strong>Title:</strong></div>
  <div id="actualTitle" class="sampleTitle"><%= @sample.title %></div>
  <div>
  <audio controls controlsList="nodownload">
    <source src="<%=@sample.audio.url()%>">
  </audio>
</div>

<div id="editButton" class="btn btn-info btn-xs"><%= link_to 'Edit', edit_sample_path(@sample) %></div>
<div id="editBack" class="btn btn-info btn-xs"><%= link_to 'Back', samples_path %></div>
</div>
</div>