config/routes.rb
Rails.application.routes.draw do
  resources :samples
  resources :paids
  resources :charges
  get "/bass" => "bass#index"
  get "/drums" => "drums#index"
  get "/effects" => "effects#index"
  get "/guitars" => "guitars#index"
  get "/synths" => "synths#index"
  get "/vocals" => "vocals#index"
  get "/members/:id" => "members#show"
  get "/users/payment_profile" => "users#payment_profile"
  get "/marketplaces" => "marketplaces#index"




get "settings/payment-info/users/auth/stripe_connect/callback", to:"users#stripe_callback"

  devise_for :users, :controllers => {:registrations => "registrations"}


  resources :samples do
    member do
      put "like", to: "samples#upvote"
      put "dislike", to: "samples#downvote"
    end
  end
  resources :paids do
    member do
      put "like", to: "paids#upvote"
      put "dislike", to: "paids#downvote"
    end
  end


  devise_scope :user do
  get 'login', to: 'devise/sessions#new'
  get 'signup', to: 'devise/registrations#new'

  authenticated  do
    root to: 'samples#index'
  end

  unauthenticated  do
    root to: 'devise/sessions#new'
  end

end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/paid.rb
class Paid < ApplicationRecord
  belongs_to :user
  mount_uploader :audio, AudioUploader
  acts_as_votable

end

app/models/sample.rb
class Sample < ApplicationRecord
  mount_uploader :audio, AudioUploader
  belongs_to :user
  acts_as_votable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :samples
  has_many :paids
  serialize :stripe_account_status, JSON
  acts_as_voter
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


def connected?; !stripe_user_id.nil?; end

def standalone?; stripe_account_type == 'standalone'; end
def oauth?; stripe_account_type == 'oauth'; end

def manager
  case stripe_account_type
  when 'standalone' then StripeStandalone.new(self)
  when 'oauth' then StripeOauth.new(self)
  end
end

def can_accept_charges?
  return true if oauth?
  return true if standalone? && stripe_account_status['charges_enabled']
  return false
end

end

app/controllers/bass_controller.rb
class BassController < ApplicationController
  def index
    @samples = Sample.where(category: "bass")
  end
end

app/controllers/marketplaces_controller.rb
class MarketplacesController < ApplicationController

  def index
    @paids = Paid.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bass_helper.rb
module BassHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/drums_helper.rb
module DrumsHelper
end

app/helpers/effects_helper.rb
module EffectsHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/guitars_helper.rb
module GuitarsHelper
end

app/helpers/marketplaces_helper.rb
module MarketplacesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/paids_helper.rb
module PaidsHelper
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/helpers/stripe_helper.rb
module StripeHelper
end

app/helpers/synths_helper.rb
module SynthsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vocals_helper.rb
module VocalsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/marketplaces/index.html.erb
<div class="profileImage">
<div class="row">
    <div id= "marketTitle" class="col-m-2 col-md-offset-4">
        <h2>Marketplace Samples</h2>
    </div>
</div>

<div id="marketSamples" class="row">
    <div id="paidSample"class="col-m-2 col-md-offset-5">
<% @paids.each do |f| %>
  <div class="paidUsername"><strong><%= f.user.username %></strong></div>
  <a id="paidLink"class="btn btn-info btn-xs" href="/paids/<%=f.id %>"><%=f.description %></a>

  <div class="marketAudio">
  <audio controls controlsList="nodownload">
    <source src="<%=f.audio.url()%>">
  </audio>
</div>

  <div class="paidTime"><%= f.created_at.strftime("%Y-%m-%d")%></div>

<div class="marketLike">
  <%= link_to like_paid_path(f), method: :put do %>
    <i class="glyphicon glyphicon-thumbs-up"></i>
    <%= f.get_upvotes.size %>
  <% end %>
  <%= link_to dislike_paid_path(f), method: :put do %>
    <i class="glyphicon glyphicon-thumbs-down"></i>
    <%= f.get_downvotes.size %>
  <% end %>
</div>
  <hr>
<% end %>

    </div>
  </div>
</div>